apiVersion: v1
kind: Service
metadata:
  name: origin-api-service
  labels:
    app: origin
    component: api
spec:
  type: ClusterIP
  selector:
    app: origin
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
