apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-api
  labels:
    app: origin
    component: api
spec:
  replicas: 2 # Start with two replicas for high availability
  selector:
    matchLabels:
      app: origin
      component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: origin
        component: api
    spec:
      containers:
      - name: api-server
        image: your-repo/origin-project:latest # Replace with your actual image repository
        imagePullPolicy: Always
        command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: origin-app-config
        - secretRef:
            name: origin-app-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
