apiVersion: v1
kind: ConfigMap
metadata:
  name: origin-app-config
data:
  # General
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DEBUG: "False"
  TESTING: "False"
  AUTH_OPTIONAL: "False"

  # LLM
  LLM_MODEL: "gpt-4o"
  LLM_PROVIDER: "openai"
  LLM_TIMEOUT: "30.0"
  LLM_MAX_RETRIES: "2"

  # Redis / Celery
  REDIS_URL: "redis://origin-redis:6379"
  CELERY_BROKER_URL: "redis://origin-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://origin-redis:6379/0"

  # Note: Sensitive values like DATABASE_URL, OPENAI_API_KEY, and DB_ENCRYPTION_KEY
  # are not stored here. They should be stored in a Kubernetes Secret.
