apiVersion: v1
kind: Secret
metadata:
  name: origin-app-secrets
type: Opaque
stringData:
  # These values should be securely managed and injected into the cluster,
  # for example, via a secrets management tool like Vault or AWS Secrets Manager.
  # The values here are for demonstration purposes only.
  DATABASE_URL: "postgresql://user:password@origin-postgres:5432/origin_db"
  OPENAI_API_KEY: "your-openai-api-key-here"
  DB_ENCRYPTION_KEY: "a-very-strong-and-long-secret-key-for-pgcrypto"
  GOOGLE_API_KEY: "your-google-api-key-here"
  GOOGLE_CSE_ID: "your-google-cse-id-here"
