apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-worker-default
  labels:
    app: origin
    component: worker
    queue: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: origin
      component: worker
      queue: default
  template:
    metadata:
      labels:
        app: origin
        component: worker
        queue: default
    spec:
      containers:
      - name: worker-default
        image: your-repo/origin-project:latest # Replace with your actual image repository
        imagePullPolicy: Always
        command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=INFO", "-P", "gevent", "-Q", "default"]
        envFrom:
        - configMapRef:
            name: origin-app-config
        - secretRef:
            name: origin-app-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
