"""Create tables for admin settings

Revision ID: 9b9d8d759b09
Revises: afd65ac9e42e
Create Date: 2025-08-29 15:42:16.245345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9d8d759b09'
down_revision: Union[str, None] = 'afd65ac9e42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('provider_configs',
        sa.Column('provider_name', sa.String(length=100), nullable=False, primary_key=True),
        sa.Column('model', sa.String(length=100), nullable=False),
        sa.Column('timeout_ms', sa.Integer(), nullable=False),
        sa.Column('retries', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'))
    )
    op.create_table('system_settings',
        sa.Column('key', sa.String(length=100), nullable=False, primary_key=True),
        sa.Column('value_json', postgresql.JSONB(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'))
    )
    op.add_column('audit_logs', sa.Column('trace_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'trace_id')
    op.drop_table('system_settings')
    op.drop_table('provider_configs')
    # ### end Alembic commands ###
