"""Add export_jobs table and tsvector index

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2025-09-06 15:08:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('export_jobs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('thread_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('format', sa.String(), nullable=False),
        sa.Column('status', sa.String(), server_default='queued', nullable=False),
        sa.Column('file_url', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['thread_id'], ['conversation_threads.id'], name=op.f('fk_export_jobs_thread_id_conversation_threads'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_user_id'), 'export_jobs', ['user_id'], unique=False)

    # Add tsvector column and index for full-text search
    op.add_column('conversation_messages', sa.Column('content_tsvector', postgresql.TSVECTOR(), nullable=True))
    op.execute("""
        CREATE INDEX idx_conversation_messages_content_tsvector
        ON conversation_messages
        USING GIN (content_tsvector);
    """)
    op.execute("""
        CREATE TRIGGER tsvector_update BEFORE INSERT OR UPDATE
        ON conversation_messages FOR EACH ROW EXECUTE PROCEDURE
        tsvector_update_trigger(content_tsvector, 'pg_catalog.english', content);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tsvector_update ON conversation_messages;")
    op.execute("DROP INDEX IF EXISTS idx_conversation_messages_content_tsvector;")
    op.drop_column('conversation_messages', 'content_tsvector')

    op.drop_index(op.f('ix_export_jobs_user_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    # ### end Alembic commands ###
