# Default panelist configuration for the multi-agent review system.
# This can be overridden at runtime via API call.
panelists:
  - provider: "openai"
    persona: "GPT-4o"
    model: "gpt-4o-mini"
    timeout_s: 45
    max_retries: 2
  - provider: "claude"
    persona: "Claude 3 Haiku"
    model: "claude-3-haiku-20240307"
    timeout_s: 45
    max_retries: 2
  - provider: "gemini"
    persona: "Gemini 1.5 Flash"
    model: "gemini-1.5-flash"
    timeout_s: 45
    max_retries: 2
