services:
  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=origin_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pgbouncer:
    image: pgbouncer/pgbouncer
    ports:
      - "6432:6432"
    environment:
      - DATABASES_HOST=db
      - DATABASES_PORT=5432
      - DATABASES_USER=user
      - DATABASES_PASSWORD=password
      - DATABASES_DBNAME=origin_db
      - POOL_MODE=session
      - LISTEN_ADDR=0.0.0.0
      - LISTEN_PORT=6432
      - AUTH_TYPE=plain
      - SERVER_RESET_QUERY=DISCARD ALL
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    build: .
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000" # Expose for direct access if needed, but primary access is via nginx
    environment:
      - DATABASE_URL=postgresql://user:password@pgbouncer:6432/origin_db
    env_file:
      - .env
    depends_on:
      - pgbouncer
      - redis

  worker-default:
    build: .
    command: celery -A app.celery_app worker --loglevel=INFO -P gevent -Q default
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@pgbouncer:6432/origin_db
    env_file:
      - .env
    depends_on:
      - pgbouncer
      - redis

  worker-high-priority:
    build: .
    command: celery -A app.celery_app worker --loglevel=INFO -P gevent -Q high_priority
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@pgbouncer:6432/origin_db
    env_file:
      - .env
    depends_on:
      - pgbouncer
      - redis

  worker-low-priority:
    build: .
    command: celery -A app.celery_app worker --loglevel=INFO -P gevent -Q low_priority
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@pgbouncer:6432/origin_db
    env_file:
      - .env
    depends_on:
      - pgbouncer
      - redis

volumes:
  postgres_data:
